//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="CATALOGUE"/&gt;
 *     &lt;enumeration value="REQUESTFORQUOTATION"/&gt;
 *     &lt;enumeration value="QUOTATION"/&gt;
 *     &lt;enumeration value="ORDER"/&gt;
 *     &lt;enumeration value="ORDERRESPONSESIMPLE"/&gt;
 *     &lt;enumeration value="REMITTANCEADVICE"/&gt;
 *     &lt;enumeration value="INVOICE"/&gt;
 *     &lt;enumeration value="APPLICATIONRESPONSE"/&gt;
 *     &lt;enumeration value="TRANSPORTATIONSTATUS"/&gt;
 *     &lt;enumeration value="DESPATCHADVICE"/&gt;
 *     &lt;enumeration value="RECEIPTADVICE"/&gt;
 *     &lt;enumeration value="PPAPRESPONSE"/&gt;
 *     &lt;enumeration value="PPAPREQUEST"/&gt;
 *     &lt;enumeration value="TRANSPORTEXECUTIONPLANREQUEST"/&gt;
 *     &lt;enumeration value="TRANSPORTEXECUTIONPLAN"/&gt;
 *     &lt;enumeration value="ITEMINFORMATIONREQUEST"/&gt;
 *     &lt;enumeration value="ITEMINFORMATIONRESPONSE"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DocumentType")
@XmlEnum
public enum DocumentType {

    CATALOGUE,
    REQUESTFORQUOTATION,
    QUOTATION,
    ORDER,
    ORDERRESPONSESIMPLE,
    REMITTANCEADVICE,
    INVOICE,
    APPLICATIONRESPONSE,
    TRANSPORTATIONSTATUS,
    DESPATCHADVICE,
    RECEIPTADVICE,
    PPAPRESPONSE,
    PPAPREQUEST,
    TRANSPORTEXECUTIONPLANREQUEST,
    TRANSPORTEXECUTIONPLAN,
    ITEMINFORMATIONREQUEST,
    ITEMINFORMATIONRESPONSE,
    OTHER;

    public String value() {
        return name();
    }

    public static DocumentType fromValue(String v) {
        return valueOf(v);
    }

}
