//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.16 at 03:08:56 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.nimble.service.bp.model.hyperjaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.nimble.service.bp.model.hyperjaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessPreferencesDAO }
     * 
     */
    public ProcessPreferencesDAO createProcessPreferencesDAO() {
        return new ProcessPreferencesDAO();
    }

    /**
     * Create an instance of {@link ProcessPreferenceDAO }
     * 
     */
    public ProcessPreferenceDAO createProcessPreferenceDAO() {
        return new ProcessPreferenceDAO();
    }

    /**
     * Create an instance of {@link ProcessDAO }
     * 
     */
    public ProcessDAO createProcessDAO() {
        return new ProcessDAO();
    }

    /**
     * Create an instance of {@link TransactionDAO }
     * 
     */
    public TransactionDAO createTransactionDAO() {
        return new TransactionDAO();
    }

    /**
     * Create an instance of {@link ExecutionConfigurationDAO }
     * 
     */
    public ExecutionConfigurationDAO createExecutionConfigurationDAO() {
        return new ExecutionConfigurationDAO();
    }

    /**
     * Create an instance of {@link TransactionConfigurationDAO }
     * 
     */
    public TransactionConfigurationDAO createTransactionConfigurationDAO() {
        return new TransactionConfigurationDAO();
    }

    /**
     * Create an instance of {@link ProcessConfigurationDAO }
     * 
     */
    public ProcessConfigurationDAO createProcessConfigurationDAO() {
        return new ProcessConfigurationDAO();
    }

    /**
     * Create an instance of {@link ProcessVariablesDAO }
     * 
     */
    public ProcessVariablesDAO createProcessVariablesDAO() {
        return new ProcessVariablesDAO();
    }

    /**
     * Create an instance of {@link ProcessInstanceInputMessageDAO }
     * 
     */
    public ProcessInstanceInputMessageDAO createProcessInstanceInputMessageDAO() {
        return new ProcessInstanceInputMessageDAO();
    }

    /**
     * Create an instance of {@link ProcessInstanceDAO }
     * 
     */
    public ProcessInstanceDAO createProcessInstanceDAO() {
        return new ProcessInstanceDAO();
    }

    /**
     * Create an instance of {@link ProcessInstanceGroupDAO }
     * 
     */
    public ProcessInstanceGroupDAO createProcessInstanceGroupDAO() {
        return new ProcessInstanceGroupDAO();
    }

    /**
     * Create an instance of {@link CollaborationGroupDAO }
     * 
     */
    public CollaborationGroupDAO createCollaborationGroupDAO() {
        return new CollaborationGroupDAO();
    }

    /**
     * Create an instance of {@link FederatedCollaborationGroupMetadataDAO }
     * 
     */
    public FederatedCollaborationGroupMetadataDAO createFederatedCollaborationGroupMetadataDAO() {
        return new FederatedCollaborationGroupMetadataDAO();
    }

    /**
     * Create an instance of {@link AssociatedProcessInstanceGroup }
     * 
     */
    public AssociatedProcessInstanceGroup createAssociatedProcessInstanceGroup() {
        return new AssociatedProcessInstanceGroup();
    }

    /**
     * Create an instance of {@link ProcessDocumentMetadataDAO }
     * 
     */
    public ProcessDocumentMetadataDAO createProcessDocumentMetadataDAO() {
        return new ProcessDocumentMetadataDAO();
    }

}
