//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessDocumentMetadataDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessDocumentMetadataDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="documentID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="submissionDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{}DocumentType"/&gt;
 *         &lt;element name="relatedProducts" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="relatedProductCategories" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{}ProcessDocumentStatus"/&gt;
 *         &lt;element name="processInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="initiatorID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="responderID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creatorUserID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessDocumentMetadataDAO", propOrder = {
    "documentID",
    "submissionDate",
    "type",
    "relatedProducts",
    "relatedProductCategories",
    "status",
    "processInstanceID",
    "initiatorID",
    "responderID",
    "creatorUserID"
})
@Entity(name = "ProcessDocumentMetadataDAO")
@Table(name = "PROCESS_DOCUMENT_METADATA_DAO", uniqueConstraints = {
        @UniqueConstraint(columnNames = {
                "DOCUMENT_ID"
        })
})
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessDocumentMetadataDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String documentID;
    @XmlElement(required = true)
    protected String submissionDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected DocumentType type;
    protected List<String> relatedProducts;
    protected List<String> relatedProductCategories;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected ProcessDocumentStatus status;
    @XmlElement(required = true)
    protected String processInstanceID;
    @XmlElement(required = true)
    protected String initiatorID;
    @XmlElement(required = true)
    protected String responderID;
    @XmlElement(required = true)
    protected String creatorUserID;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem> relatedProductsItems;
    protected transient List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem> relatedProductCategoriesItems;

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DOCUMENT_ID", length = 255)
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SUBMISSION_DATE", length = 255)
    public String getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionDate(String value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    @Basic
    @Column(name = "TYPE_", length = 255)
    @Enumerated(EnumType.STRING)
    public DocumentType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setType(DocumentType value) {
        this.type = value;
    }

    /**
     * Gets the value of the relatedProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getRelatedProducts() {
        if (relatedProducts == null) {
            relatedProducts = new ArrayList<String>();
        }
        return this.relatedProducts;
    }

    /**
     * 
     * 
     */
    public void setRelatedProducts(List<String> relatedProducts) {
        this.relatedProducts = relatedProducts;
    }

    /**
     * Gets the value of the relatedProductCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedProductCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedProductCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getRelatedProductCategories() {
        if (relatedProductCategories == null) {
            relatedProductCategories = new ArrayList<String>();
        }
        return this.relatedProductCategories;
    }

    /**
     * 
     * 
     */
    public void setRelatedProductCategories(List<String> relatedProductCategories) {
        this.relatedProductCategories = relatedProductCategories;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDocumentStatus }
     *     
     */
    @Basic
    @Column(name = "STATUS", length = 255)
    @Enumerated(EnumType.STRING)
    public ProcessDocumentStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDocumentStatus }
     *     
     */
    public void setStatus(ProcessDocumentStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the processInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_INSTANCE_ID", length = 255)
    public String getProcessInstanceID() {
        return processInstanceID;
    }

    /**
     * Sets the value of the processInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceID(String value) {
        this.processInstanceID = value;
    }

    /**
     * Gets the value of the initiatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "INITIATOR_ID", length = 255)
    public String getInitiatorID() {
        return initiatorID;
    }

    /**
     * Sets the value of the initiatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorID(String value) {
        this.initiatorID = value;
    }

    /**
     * Gets the value of the responderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "RESPONDER_ID", length = 255)
    public String getResponderID() {
        return responderID;
    }

    /**
     * Sets the value of the responderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponderID(String value) {
        this.responderID = value;
    }

    /**
     * Gets the value of the creatorUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CREATOR_USER_ID", length = 255)
    public String getCreatorUserID() {
        return creatorUserID;
    }

    /**
     * Sets the value of the creatorUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorUserID(String value) {
        this.creatorUserID = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessDocumentMetadataDAO that = ((ProcessDocumentMetadataDAO) object);
        {
            String lhsDocumentID;
            lhsDocumentID = this.getDocumentID();
            String rhsDocumentID;
            rhsDocumentID = that.getDocumentID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentID", lhsDocumentID), LocatorUtils.property(thatLocator, "documentID", rhsDocumentID), lhsDocumentID, rhsDocumentID)) {
                return false;
            }
        }
        {
            String lhsSubmissionDate;
            lhsSubmissionDate = this.getSubmissionDate();
            String rhsSubmissionDate;
            rhsSubmissionDate = that.getSubmissionDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "submissionDate", lhsSubmissionDate), LocatorUtils.property(thatLocator, "submissionDate", rhsSubmissionDate), lhsSubmissionDate, rhsSubmissionDate)) {
                return false;
            }
        }
        {
            DocumentType lhsType;
            lhsType = this.getType();
            DocumentType rhsType;
            rhsType = that.getType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsType), LocatorUtils.property(thatLocator, "type", rhsType), lhsType, rhsType)) {
                return false;
            }
        }
        {
            List<String> lhsRelatedProducts;
            lhsRelatedProducts = (((this.relatedProducts!= null)&&(!this.relatedProducts.isEmpty()))?this.getRelatedProducts():null);
            List<String> rhsRelatedProducts;
            rhsRelatedProducts = (((that.relatedProducts!= null)&&(!that.relatedProducts.isEmpty()))?that.getRelatedProducts():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "relatedProducts", lhsRelatedProducts), LocatorUtils.property(thatLocator, "relatedProducts", rhsRelatedProducts), lhsRelatedProducts, rhsRelatedProducts)) {
                return false;
            }
        }
        {
            List<String> lhsRelatedProductCategories;
            lhsRelatedProductCategories = (((this.relatedProductCategories!= null)&&(!this.relatedProductCategories.isEmpty()))?this.getRelatedProductCategories():null);
            List<String> rhsRelatedProductCategories;
            rhsRelatedProductCategories = (((that.relatedProductCategories!= null)&&(!that.relatedProductCategories.isEmpty()))?that.getRelatedProductCategories():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "relatedProductCategories", lhsRelatedProductCategories), LocatorUtils.property(thatLocator, "relatedProductCategories", rhsRelatedProductCategories), lhsRelatedProductCategories, rhsRelatedProductCategories)) {
                return false;
            }
        }
        {
            ProcessDocumentStatus lhsStatus;
            lhsStatus = this.getStatus();
            ProcessDocumentStatus rhsStatus;
            rhsStatus = that.getStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "status", lhsStatus), LocatorUtils.property(thatLocator, "status", rhsStatus), lhsStatus, rhsStatus)) {
                return false;
            }
        }
        {
            String lhsProcessInstanceID;
            lhsProcessInstanceID = this.getProcessInstanceID();
            String rhsProcessInstanceID;
            rhsProcessInstanceID = that.getProcessInstanceID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processInstanceID", lhsProcessInstanceID), LocatorUtils.property(thatLocator, "processInstanceID", rhsProcessInstanceID), lhsProcessInstanceID, rhsProcessInstanceID)) {
                return false;
            }
        }
        {
            String lhsInitiatorID;
            lhsInitiatorID = this.getInitiatorID();
            String rhsInitiatorID;
            rhsInitiatorID = that.getInitiatorID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "initiatorID", lhsInitiatorID), LocatorUtils.property(thatLocator, "initiatorID", rhsInitiatorID), lhsInitiatorID, rhsInitiatorID)) {
                return false;
            }
        }
        {
            String lhsResponderID;
            lhsResponderID = this.getResponderID();
            String rhsResponderID;
            rhsResponderID = that.getResponderID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "responderID", lhsResponderID), LocatorUtils.property(thatLocator, "responderID", rhsResponderID), lhsResponderID, rhsResponderID)) {
                return false;
            }
        }
        {
            String lhsCreatorUserID;
            lhsCreatorUserID = this.getCreatorUserID();
            String rhsCreatorUserID;
            rhsCreatorUserID = that.getCreatorUserID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "creatorUserID", lhsCreatorUserID), LocatorUtils.property(thatLocator, "creatorUserID", rhsCreatorUserID), lhsCreatorUserID, rhsCreatorUserID)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RELATED_PRODUCTS_ITEMS_PROCE_1")
    public List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem> getRelatedProductsItems() {
        if (this.relatedProductsItems == null) {
            this.relatedProductsItems = new ArrayList<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProducts)) {
            this.relatedProducts = ItemUtils.wrap(this.relatedProducts, this.relatedProductsItems, ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem.class);
        }
        return this.relatedProductsItems;
    }

    public void setRelatedProductsItems(List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem> value) {
        this.relatedProducts = null;
        this.relatedProductsItems = null;
        this.relatedProductsItems = value;
        if (this.relatedProductsItems == null) {
            this.relatedProductsItems = new ArrayList<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProducts)) {
            this.relatedProducts = ItemUtils.wrap(this.relatedProducts, this.relatedProductsItems, ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductsItem.class);
        }
    }

    @OneToMany(targetEntity = ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RELATED_PRODUCT_CATEGORIES_I_2")
    public List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem> getRelatedProductCategoriesItems() {
        if (this.relatedProductCategoriesItems == null) {
            this.relatedProductCategoriesItems = new ArrayList<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProductCategories)) {
            this.relatedProductCategories = ItemUtils.wrap(this.relatedProductCategories, this.relatedProductCategoriesItems, ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem.class);
        }
        return this.relatedProductCategoriesItems;
    }

    public void setRelatedProductCategoriesItems(List<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem> value) {
        this.relatedProductCategories = null;
        this.relatedProductCategoriesItems = null;
        this.relatedProductCategoriesItems = value;
        if (this.relatedProductCategoriesItems == null) {
            this.relatedProductCategoriesItems = new ArrayList<ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProductCategories)) {
            this.relatedProductCategories = ItemUtils.wrap(this.relatedProductCategories, this.relatedProductCategoriesItems, ProcessDocumentMetadataDAO.ProcessDocumentMetadataDAORelatedProductCategoriesItem.class);
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ProcessDocumentMetadataDAO$ProcessDocumentMetadataDAORelatedProductCategoriesItem")
    @Table(name = "PROCESS_DOCUMENT_METADATA_DA_0")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class ProcessDocumentMetadataDAORelatedProductCategoriesItem
        implements Item<String>
    {

        @XmlElement(name = "relatedProductCategories")
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ProcessDocumentMetadataDAO$ProcessDocumentMetadataDAORelatedProductsItem")
    @Table(name = "PROCESS_DOCUMENT_METADATA_DA_1")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class ProcessDocumentMetadataDAORelatedProductsItem
        implements Item<String>
    {

        @XmlElement(name = "relatedProducts")
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
