//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessPreferenceDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessPreferenceDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="targetPartnerID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processOrder" type="{}ProcessType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessPreferenceDAO", propOrder = {
    "targetPartnerID",
    "processOrder"
})
@Entity(name = "ProcessPreferenceDAO")
@Table(name = "PROCESS_PREFERENCE_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessPreferenceDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String targetPartnerID;
    @XmlElement(required = true)
    protected List<ProcessType> processOrder;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem> processOrderItems;

    /**
     * Gets the value of the targetPartnerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TARGET_PARTNER_ID", length = 255)
    public String getTargetPartnerID() {
        return targetPartnerID;
    }

    /**
     * Sets the value of the targetPartnerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetPartnerID(String value) {
        this.targetPartnerID = value;
    }

    /**
     * Gets the value of the processOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessType }
     * 
     * 
     */
    @Transient
    public List<ProcessType> getProcessOrder() {
        if (processOrder == null) {
            processOrder = new ArrayList<ProcessType>();
        }
        return this.processOrder;
    }

    /**
     * 
     * 
     */
    public void setProcessOrder(List<ProcessType> processOrder) {
        this.processOrder = processOrder;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessPreferenceDAO that = ((ProcessPreferenceDAO) object);
        {
            String lhsTargetPartnerID;
            lhsTargetPartnerID = this.getTargetPartnerID();
            String rhsTargetPartnerID;
            rhsTargetPartnerID = that.getTargetPartnerID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "targetPartnerID", lhsTargetPartnerID), LocatorUtils.property(thatLocator, "targetPartnerID", rhsTargetPartnerID), lhsTargetPartnerID, rhsTargetPartnerID)) {
                return false;
            }
        }
        {
            List<ProcessType> lhsProcessOrder;
            lhsProcessOrder = (((this.processOrder!= null)&&(!this.processOrder.isEmpty()))?this.getProcessOrder():null);
            List<ProcessType> rhsProcessOrder;
            rhsProcessOrder = (((that.processOrder!= null)&&(!that.processOrder.isEmpty()))?that.getProcessOrder():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processOrder", lhsProcessOrder), LocatorUtils.property(thatLocator, "processOrder", rhsProcessOrder), lhsProcessOrder, rhsProcessOrder)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PROCESS_ORDER_ITEMS_PROCESS__0")
    public List<ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem> getProcessOrderItems() {
        if (this.processOrderItems == null) {
            this.processOrderItems = new ArrayList<ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.processOrder)) {
            this.processOrder = ItemUtils.wrap(this.processOrder, this.processOrderItems, ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem.class);
        }
        return this.processOrderItems;
    }

    public void setProcessOrderItems(List<ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem> value) {
        this.processOrder = null;
        this.processOrderItems = null;
        this.processOrderItems = value;
        if (this.processOrderItems == null) {
            this.processOrderItems = new ArrayList<ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.processOrder)) {
            this.processOrder = ItemUtils.wrap(this.processOrder, this.processOrderItems, ProcessPreferenceDAO.ProcessPreferenceDAOProcessOrderItem.class);
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ProcessPreferenceDAO$ProcessPreferenceDAOProcessOrderItem")
    @Table(name = "PROCESS_PREFERENCE_DAOPROCES_0")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class ProcessPreferenceDAOProcessOrderItem
        implements Item<ProcessType>
    {

        @XmlElement(name = "processOrder")
        @XmlSchemaType(name = "token")
        protected ProcessType item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link ProcessType }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        @Enumerated(EnumType.STRING)
        public ProcessType getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProcessType }
         *     
         */
        public void setItem(ProcessType value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
