//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessVariablesDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessVariablesDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="processID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="initiatorID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="responderID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creatorUserID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contentUUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="relatedProducts" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="relatedProductCategories" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessVariablesDAO", propOrder = {
    "processID",
    "initiatorID",
    "responderID",
    "creatorUserID",
    "contentUUID",
    "relatedProducts",
    "relatedProductCategories"
})
@Entity(name = "ProcessVariablesDAO")
@Table(name = "PROCESS_VARIABLES_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessVariablesDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String processID;
    @XmlElement(required = true)
    protected String initiatorID;
    @XmlElement(required = true)
    protected String responderID;
    @XmlElement(required = true)
    protected String creatorUserID;
    @XmlElement(required = true)
    protected String contentUUID;
    protected List<String> relatedProducts;
    protected List<String> relatedProductCategories;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem> relatedProductsItems;
    protected transient List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem> relatedProductCategoriesItems;

    /**
     * Gets the value of the processID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_ID", length = 255)
    public String getProcessID() {
        return processID;
    }

    /**
     * Sets the value of the processID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessID(String value) {
        this.processID = value;
    }

    /**
     * Gets the value of the initiatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "INITIATOR_ID", length = 255)
    public String getInitiatorID() {
        return initiatorID;
    }

    /**
     * Sets the value of the initiatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorID(String value) {
        this.initiatorID = value;
    }

    /**
     * Gets the value of the responderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "RESPONDER_ID", length = 255)
    public String getResponderID() {
        return responderID;
    }

    /**
     * Sets the value of the responderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponderID(String value) {
        this.responderID = value;
    }

    /**
     * Gets the value of the creatorUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CREATOR_USER_ID", length = 255)
    public String getCreatorUserID() {
        return creatorUserID;
    }

    /**
     * Sets the value of the creatorUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorUserID(String value) {
        this.creatorUserID = value;
    }

    /**
     * Gets the value of the contentUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CONTENT_UUID", length = 255)
    public String getContentUUID() {
        return contentUUID;
    }

    /**
     * Sets the value of the contentUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentUUID(String value) {
        this.contentUUID = value;
    }

    /**
     * Gets the value of the relatedProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getRelatedProducts() {
        if (relatedProducts == null) {
            relatedProducts = new ArrayList<String>();
        }
        return this.relatedProducts;
    }

    /**
     * 
     * 
     */
    public void setRelatedProducts(List<String> relatedProducts) {
        this.relatedProducts = relatedProducts;
    }

    /**
     * Gets the value of the relatedProductCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedProductCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedProductCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getRelatedProductCategories() {
        if (relatedProductCategories == null) {
            relatedProductCategories = new ArrayList<String>();
        }
        return this.relatedProductCategories;
    }

    /**
     * 
     * 
     */
    public void setRelatedProductCategories(List<String> relatedProductCategories) {
        this.relatedProductCategories = relatedProductCategories;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessVariablesDAO that = ((ProcessVariablesDAO) object);
        {
            String lhsProcessID;
            lhsProcessID = this.getProcessID();
            String rhsProcessID;
            rhsProcessID = that.getProcessID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processID", lhsProcessID), LocatorUtils.property(thatLocator, "processID", rhsProcessID), lhsProcessID, rhsProcessID)) {
                return false;
            }
        }
        {
            String lhsInitiatorID;
            lhsInitiatorID = this.getInitiatorID();
            String rhsInitiatorID;
            rhsInitiatorID = that.getInitiatorID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "initiatorID", lhsInitiatorID), LocatorUtils.property(thatLocator, "initiatorID", rhsInitiatorID), lhsInitiatorID, rhsInitiatorID)) {
                return false;
            }
        }
        {
            String lhsResponderID;
            lhsResponderID = this.getResponderID();
            String rhsResponderID;
            rhsResponderID = that.getResponderID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "responderID", lhsResponderID), LocatorUtils.property(thatLocator, "responderID", rhsResponderID), lhsResponderID, rhsResponderID)) {
                return false;
            }
        }
        {
            String lhsCreatorUserID;
            lhsCreatorUserID = this.getCreatorUserID();
            String rhsCreatorUserID;
            rhsCreatorUserID = that.getCreatorUserID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "creatorUserID", lhsCreatorUserID), LocatorUtils.property(thatLocator, "creatorUserID", rhsCreatorUserID), lhsCreatorUserID, rhsCreatorUserID)) {
                return false;
            }
        }
        {
            String lhsContentUUID;
            lhsContentUUID = this.getContentUUID();
            String rhsContentUUID;
            rhsContentUUID = that.getContentUUID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "contentUUID", lhsContentUUID), LocatorUtils.property(thatLocator, "contentUUID", rhsContentUUID), lhsContentUUID, rhsContentUUID)) {
                return false;
            }
        }
        {
            List<String> lhsRelatedProducts;
            lhsRelatedProducts = (((this.relatedProducts!= null)&&(!this.relatedProducts.isEmpty()))?this.getRelatedProducts():null);
            List<String> rhsRelatedProducts;
            rhsRelatedProducts = (((that.relatedProducts!= null)&&(!that.relatedProducts.isEmpty()))?that.getRelatedProducts():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "relatedProducts", lhsRelatedProducts), LocatorUtils.property(thatLocator, "relatedProducts", rhsRelatedProducts), lhsRelatedProducts, rhsRelatedProducts)) {
                return false;
            }
        }
        {
            List<String> lhsRelatedProductCategories;
            lhsRelatedProductCategories = (((this.relatedProductCategories!= null)&&(!this.relatedProductCategories.isEmpty()))?this.getRelatedProductCategories():null);
            List<String> rhsRelatedProductCategories;
            rhsRelatedProductCategories = (((that.relatedProductCategories!= null)&&(!that.relatedProductCategories.isEmpty()))?that.getRelatedProductCategories():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "relatedProductCategories", lhsRelatedProductCategories), LocatorUtils.property(thatLocator, "relatedProductCategories", rhsRelatedProductCategories), lhsRelatedProductCategories, rhsRelatedProductCategories)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RELATED_PRODUCTS_ITEMS_PROCE_0")
    public List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem> getRelatedProductsItems() {
        if (this.relatedProductsItems == null) {
            this.relatedProductsItems = new ArrayList<ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProducts)) {
            this.relatedProducts = ItemUtils.wrap(this.relatedProducts, this.relatedProductsItems, ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem.class);
        }
        return this.relatedProductsItems;
    }

    public void setRelatedProductsItems(List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem> value) {
        this.relatedProducts = null;
        this.relatedProductsItems = null;
        this.relatedProductsItems = value;
        if (this.relatedProductsItems == null) {
            this.relatedProductsItems = new ArrayList<ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProducts)) {
            this.relatedProducts = ItemUtils.wrap(this.relatedProducts, this.relatedProductsItems, ProcessVariablesDAO.ProcessVariablesDAORelatedProductsItem.class);
        }
    }

    @OneToMany(targetEntity = ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RELATED_PRODUCT_CATEGORIES_I_1")
    public List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem> getRelatedProductCategoriesItems() {
        if (this.relatedProductCategoriesItems == null) {
            this.relatedProductCategoriesItems = new ArrayList<ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProductCategories)) {
            this.relatedProductCategories = ItemUtils.wrap(this.relatedProductCategories, this.relatedProductCategoriesItems, ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem.class);
        }
        return this.relatedProductCategoriesItems;
    }

    public void setRelatedProductCategoriesItems(List<ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem> value) {
        this.relatedProductCategories = null;
        this.relatedProductCategoriesItems = null;
        this.relatedProductCategoriesItems = value;
        if (this.relatedProductCategoriesItems == null) {
            this.relatedProductCategoriesItems = new ArrayList<ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.relatedProductCategories)) {
            this.relatedProductCategories = ItemUtils.wrap(this.relatedProductCategories, this.relatedProductCategoriesItems, ProcessVariablesDAO.ProcessVariablesDAORelatedProductCategoriesItem.class);
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ProcessVariablesDAO$ProcessVariablesDAORelatedProductCategoriesItem")
    @Table(name = "PROCESS_VARIABLES_DAORELATED_0")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class ProcessVariablesDAORelatedProductCategoriesItem
        implements Item<String>
    {

        @XmlElement(name = "relatedProductCategories")
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ProcessVariablesDAO$ProcessVariablesDAORelatedProductsItem")
    @Table(name = "PROCESS_VARIABLES_DAORELATED_1")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class ProcessVariablesDAORelatedProductsItem
        implements Item<String>
    {

        @XmlElement(name = "relatedProducts")
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
