//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.model.hyperjaxb;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for TransactionDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="initiatorRole" type="{}RoleType"/&gt;
 *         &lt;element name="responderRole" type="{}RoleType"/&gt;
 *         &lt;element name="documentType" type="{}DocumentType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDAO", propOrder = {
    "transactionID",
    "initiatorRole",
    "responderRole",
    "documentType"
})
@Entity(name = "TransactionDAO")
@Table(name = "TRANSACTION_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class TransactionDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String transactionID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected RoleType initiatorRole;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected RoleType responderRole;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected DocumentType documentType;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TRANSACTION_ID", length = 255)
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the initiatorRole property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    @Basic
    @Column(name = "INITIATOR_ROLE", length = 255)
    @Enumerated(EnumType.STRING)
    public RoleType getInitiatorRole() {
        return initiatorRole;
    }

    /**
     * Sets the value of the initiatorRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setInitiatorRole(RoleType value) {
        this.initiatorRole = value;
    }

    /**
     * Gets the value of the responderRole property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    @Basic
    @Column(name = "RESPONDER_ROLE", length = 255)
    @Enumerated(EnumType.STRING)
    public RoleType getResponderRole() {
        return responderRole;
    }

    /**
     * Sets the value of the responderRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setResponderRole(RoleType value) {
        this.responderRole = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    @Basic
    @Column(name = "DOCUMENT_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public DocumentType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setDocumentType(DocumentType value) {
        this.documentType = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TransactionDAO that = ((TransactionDAO) object);
        {
            String lhsTransactionID;
            lhsTransactionID = this.getTransactionID();
            String rhsTransactionID;
            rhsTransactionID = that.getTransactionID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transactionID", lhsTransactionID), LocatorUtils.property(thatLocator, "transactionID", rhsTransactionID), lhsTransactionID, rhsTransactionID)) {
                return false;
            }
        }
        {
            RoleType lhsInitiatorRole;
            lhsInitiatorRole = this.getInitiatorRole();
            RoleType rhsInitiatorRole;
            rhsInitiatorRole = that.getInitiatorRole();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "initiatorRole", lhsInitiatorRole), LocatorUtils.property(thatLocator, "initiatorRole", rhsInitiatorRole), lhsInitiatorRole, rhsInitiatorRole)) {
                return false;
            }
        }
        {
            RoleType lhsResponderRole;
            lhsResponderRole = this.getResponderRole();
            RoleType rhsResponderRole;
            rhsResponderRole = that.getResponderRole();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "responderRole", lhsResponderRole), LocatorUtils.property(thatLocator, "responderRole", rhsResponderRole), lhsResponderRole, rhsResponderRole)) {
                return false;
            }
        }
        {
            DocumentType lhsDocumentType;
            lhsDocumentType = this.getDocumentType();
            DocumentType rhsDocumentType;
            rhsDocumentType = that.getDocumentType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentType", lhsDocumentType), LocatorUtils.property(thatLocator, "documentType", rhsDocumentType), lhsDocumentType, rhsDocumentType)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
