//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for AssociatedProcessInstanceGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedProcessInstanceGroup"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="processInstances" type="{}ProcessInstanceGroupDAO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedProcessInstanceGroup", propOrder = {
    "processInstances"
})
@Entity(name = "AssociatedProcessInstanceGroup")
@Table(name = "ASSOCIATED_PROCESS_INSTANCE__0")
@Inheritance(strategy = InheritanceType.JOINED)
public class AssociatedProcessInstanceGroup
    implements Equals
{

    @XmlElement(required = true)
    protected ProcessInstanceGroupDAO processInstances;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the processInstances property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessInstanceGroupDAO }
     *     
     */
    @ManyToOne(targetEntity = ProcessInstanceGroupDAO.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PROCESS_INSTANCES_ASSOCIATED_0")
    public ProcessInstanceGroupDAO getProcessInstances() {
        return processInstances;
    }

    /**
     * Sets the value of the processInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessInstanceGroupDAO }
     *     
     */
    public void setProcessInstances(ProcessInstanceGroupDAO value) {
        this.processInstances = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AssociatedProcessInstanceGroup that = ((AssociatedProcessInstanceGroup) object);
        {
            ProcessInstanceGroupDAO lhsProcessInstances;
            lhsProcessInstances = this.getProcessInstances();
            ProcessInstanceGroupDAO rhsProcessInstances;
            rhsProcessInstances = that.getProcessInstances();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processInstances", lhsProcessInstances), LocatorUtils.property(thatLocator, "processInstances", rhsProcessInstances), lhsProcessInstances, rhsProcessInstances)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
