//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ExecutionConfigurationDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExecutionConfigurationDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicationType" type="{}ApplicationType"/&gt;
 *         &lt;element name="executionType" type="{}ApplicationExecutionType"/&gt;
 *         &lt;element name="executionUri" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExecutionConfigurationDAO", propOrder = {
    "applicationType",
    "executionType",
    "executionUri"
})
@Entity(name = "ExecutionConfigurationDAO")
@Table(name = "EXECUTION_CONFIGURATION_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ExecutionConfigurationDAO
    implements Equals
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected ApplicationType applicationType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected ApplicationExecutionType executionType;
    @XmlElement(required = true)
    protected String executionUri;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the applicationType property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationType }
     *     
     */
    @Basic
    @Column(name = "APPLICATION_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public ApplicationType getApplicationType() {
        return applicationType;
    }

    /**
     * Sets the value of the applicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationType }
     *     
     */
    public void setApplicationType(ApplicationType value) {
        this.applicationType = value;
    }

    /**
     * Gets the value of the executionType property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationExecutionType }
     *     
     */
    @Basic
    @Column(name = "EXECUTION_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public ApplicationExecutionType getExecutionType() {
        return executionType;
    }

    /**
     * Sets the value of the executionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationExecutionType }
     *     
     */
    public void setExecutionType(ApplicationExecutionType value) {
        this.executionType = value;
    }

    /**
     * Gets the value of the executionUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EXECUTION_URI", length = 255)
    public String getExecutionUri() {
        return executionUri;
    }

    /**
     * Sets the value of the executionUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutionUri(String value) {
        this.executionUri = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ExecutionConfigurationDAO that = ((ExecutionConfigurationDAO) object);
        {
            ApplicationType lhsApplicationType;
            lhsApplicationType = this.getApplicationType();
            ApplicationType rhsApplicationType;
            rhsApplicationType = that.getApplicationType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "applicationType", lhsApplicationType), LocatorUtils.property(thatLocator, "applicationType", rhsApplicationType), lhsApplicationType, rhsApplicationType)) {
                return false;
            }
        }
        {
            ApplicationExecutionType lhsExecutionType;
            lhsExecutionType = this.getExecutionType();
            ApplicationExecutionType rhsExecutionType;
            rhsExecutionType = that.getExecutionType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "executionType", lhsExecutionType), LocatorUtils.property(thatLocator, "executionType", rhsExecutionType), lhsExecutionType, rhsExecutionType)) {
                return false;
            }
        }
        {
            String lhsExecutionUri;
            lhsExecutionUri = this.getExecutionUri();
            String rhsExecutionUri;
            rhsExecutionUri = that.getExecutionUri();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "executionUri", lhsExecutionUri), LocatorUtils.property(thatLocator, "executionUri", rhsExecutionUri), lhsExecutionUri, rhsExecutionUri)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
