//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessInstanceInputMessageDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessInstanceInputMessageDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="variables" type="{}ProcessVariablesDAO"/&gt;
 *         &lt;element name="processInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessInstanceInputMessageDAO", propOrder = {
    "variables",
    "processInstanceID"
})
@Entity(name = "ProcessInstanceInputMessageDAO")
@Table(name = "PROCESS_INSTANCE_INPUT_MESSA_0")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessInstanceInputMessageDAO
    implements Equals
{

    @XmlElement(required = true)
    protected ProcessVariablesDAO variables;
    @XmlElement(required = true)
    protected String processInstanceID;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessVariablesDAO }
     *     
     */
    @ManyToOne(targetEntity = ProcessVariablesDAO.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "VARIABLES_PROCESS_INSTANCE_I_0")
    public ProcessVariablesDAO getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessVariablesDAO }
     *     
     */
    public void setVariables(ProcessVariablesDAO value) {
        this.variables = value;
    }

    /**
     * Gets the value of the processInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_INSTANCE_ID", length = 255)
    public String getProcessInstanceID() {
        return processInstanceID;
    }

    /**
     * Sets the value of the processInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceID(String value) {
        this.processInstanceID = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessInstanceInputMessageDAO that = ((ProcessInstanceInputMessageDAO) object);
        {
            ProcessVariablesDAO lhsVariables;
            lhsVariables = this.getVariables();
            ProcessVariablesDAO rhsVariables;
            rhsVariables = that.getVariables();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "variables", lhsVariables), LocatorUtils.property(thatLocator, "variables", rhsVariables), lhsVariables, rhsVariables)) {
                return false;
            }
        }
        {
            String lhsProcessInstanceID;
            lhsProcessInstanceID = this.getProcessInstanceID();
            String rhsProcessInstanceID;
            rhsProcessInstanceID = that.getProcessInstanceID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processInstanceID", lhsProcessInstanceID), LocatorUtils.property(thatLocator, "processInstanceID", rhsProcessInstanceID), lhsProcessInstanceID, rhsProcessInstanceID)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
