//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessConfigurationDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessConfigurationDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="partnerID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="roleType" type="{}RoleType"/&gt;
 *         &lt;element name="processID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transactionConfigurations" type="{}TransactionConfigurationDAO" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessConfigurationDAO", propOrder = {
    "partnerID",
    "roleType",
    "processID",
    "transactionConfigurations"
})
@Entity(name = "ProcessConfigurationDAO")
@Table(name = "PROCESS_CONFIGURATION_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessConfigurationDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String partnerID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected RoleType roleType;
    @XmlElement(required = true)
    protected String processID;
    @XmlElement(required = true)
    protected List<TransactionConfigurationDAO> transactionConfigurations;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the partnerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PARTNER_ID", length = 255)
    public String getPartnerID() {
        return partnerID;
    }

    /**
     * Sets the value of the partnerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerID(String value) {
        this.partnerID = value;
    }

    /**
     * Gets the value of the roleType property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    @Basic
    @Column(name = "ROLE_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public RoleType getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setRoleType(RoleType value) {
        this.roleType = value;
    }

    /**
     * Gets the value of the processID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_ID", length = 255)
    public String getProcessID() {
        return processID;
    }

    /**
     * Sets the value of the processID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessID(String value) {
        this.processID = value;
    }

    /**
     * Gets the value of the transactionConfigurations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactionConfigurations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactionConfigurations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionConfigurationDAO }
     * 
     * 
     */
    @OneToMany(targetEntity = TransactionConfigurationDAO.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRANSACTION_CONFIGURATIONS_P_0")
    public List<TransactionConfigurationDAO> getTransactionConfigurations() {
        if (transactionConfigurations == null) {
            transactionConfigurations = new ArrayList<TransactionConfigurationDAO>();
        }
        return this.transactionConfigurations;
    }

    /**
     * 
     * 
     */
    public void setTransactionConfigurations(List<TransactionConfigurationDAO> transactionConfigurations) {
        this.transactionConfigurations = transactionConfigurations;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessConfigurationDAO that = ((ProcessConfigurationDAO) object);
        {
            String lhsPartnerID;
            lhsPartnerID = this.getPartnerID();
            String rhsPartnerID;
            rhsPartnerID = that.getPartnerID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "partnerID", lhsPartnerID), LocatorUtils.property(thatLocator, "partnerID", rhsPartnerID), lhsPartnerID, rhsPartnerID)) {
                return false;
            }
        }
        {
            RoleType lhsRoleType;
            lhsRoleType = this.getRoleType();
            RoleType rhsRoleType;
            rhsRoleType = that.getRoleType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "roleType", lhsRoleType), LocatorUtils.property(thatLocator, "roleType", rhsRoleType), lhsRoleType, rhsRoleType)) {
                return false;
            }
        }
        {
            String lhsProcessID;
            lhsProcessID = this.getProcessID();
            String rhsProcessID;
            rhsProcessID = that.getProcessID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processID", lhsProcessID), LocatorUtils.property(thatLocator, "processID", rhsProcessID), lhsProcessID, rhsProcessID)) {
                return false;
            }
        }
        {
            List<TransactionConfigurationDAO> lhsTransactionConfigurations;
            lhsTransactionConfigurations = (((this.transactionConfigurations!= null)&&(!this.transactionConfigurations.isEmpty()))?this.getTransactionConfigurations():null);
            List<TransactionConfigurationDAO> rhsTransactionConfigurations;
            rhsTransactionConfigurations = (((that.transactionConfigurations!= null)&&(!that.transactionConfigurations.isEmpty()))?that.getTransactionConfigurations():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transactionConfigurations", lhsTransactionConfigurations), LocatorUtils.property(thatLocator, "transactionConfigurations", rhsTransactionConfigurations), lhsTransactionConfigurations, rhsTransactionConfigurations)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
