//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ProcessDAO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessDAO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="processID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="textContent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processType" type="{}ProcessType"/&gt;
 *         &lt;element name="transactions" type="{}TransactionDAO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessDAO", propOrder = {
    "processID",
    "processName",
    "textContent",
    "processType",
    "transactions"
})
@Entity(name = "ProcessDAO")
@Table(name = "PROCESS_DAO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProcessDAO
    implements Equals
{

    @XmlElement(required = true)
    protected String processID;
    @XmlElement(required = true)
    protected String processName;
    @XmlElement(required = true)
    protected String textContent;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected ProcessType processType;
    protected List<TransactionDAO> transactions;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the processID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_ID", length = 255)
    public String getProcessID() {
        return processID;
    }

    /**
     * Sets the value of the processID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessID(String value) {
        this.processID = value;
    }

    /**
     * Gets the value of the processName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROCESS_NAME", length = 255)
    public String getProcessName() {
        return processName;
    }

    /**
     * Sets the value of the processName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessName(String value) {
        this.processName = value;
    }

    /**
     * Gets the value of the textContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TEXT_CONTENT", length = 255)
    public String getTextContent() {
        return textContent;
    }

    /**
     * Sets the value of the textContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextContent(String value) {
        this.textContent = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    @Basic
    @Column(name = "PROCESS_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public ProcessType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessType(ProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionDAO }
     * 
     * 
     */
    @OneToMany(targetEntity = TransactionDAO.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRANSACTIONS_PROCESS_DAO_HJID")
    public List<TransactionDAO> getTransactions() {
        if (transactions == null) {
            transactions = new ArrayList<TransactionDAO>();
        }
        return this.transactions;
    }

    /**
     * 
     * 
     */
    public void setTransactions(List<TransactionDAO> transactions) {
        this.transactions = transactions;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcessDAO that = ((ProcessDAO) object);
        {
            String lhsProcessID;
            lhsProcessID = this.getProcessID();
            String rhsProcessID;
            rhsProcessID = that.getProcessID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processID", lhsProcessID), LocatorUtils.property(thatLocator, "processID", rhsProcessID), lhsProcessID, rhsProcessID)) {
                return false;
            }
        }
        {
            String lhsProcessName;
            lhsProcessName = this.getProcessName();
            String rhsProcessName;
            rhsProcessName = that.getProcessName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processName", lhsProcessName), LocatorUtils.property(thatLocator, "processName", rhsProcessName), lhsProcessName, rhsProcessName)) {
                return false;
            }
        }
        {
            String lhsTextContent;
            lhsTextContent = this.getTextContent();
            String rhsTextContent;
            rhsTextContent = that.getTextContent();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "textContent", lhsTextContent), LocatorUtils.property(thatLocator, "textContent", rhsTextContent), lhsTextContent, rhsTextContent)) {
                return false;
            }
        }
        {
            ProcessType lhsProcessType;
            lhsProcessType = this.getProcessType();
            ProcessType rhsProcessType;
            rhsProcessType = that.getProcessType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processType", lhsProcessType), LocatorUtils.property(thatLocator, "processType", rhsProcessType), lhsProcessType, rhsProcessType)) {
                return false;
            }
        }
        {
            List<TransactionDAO> lhsTransactions;
            lhsTransactions = (((this.transactions!= null)&&(!this.transactions.isEmpty()))?this.getTransactions():null);
            List<TransactionDAO> rhsTransactions;
            rhsTransactions = (((that.transactions!= null)&&(!that.transactions.isEmpty()))?that.getTransactions():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transactions", lhsTransactions), LocatorUtils.property(thatLocator, "transactions", rhsTransactions), lhsTransactions, rhsTransactions)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
