//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 03:26:39 PM EET 
//


package eu.nimble.service.bp.hyperjaxb.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessDocumentStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessDocumentStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="APPROVED"/&gt;
 *     &lt;enumeration value="WAITINGRESPONSE"/&gt;
 *     &lt;enumeration value="DENIED"/&gt;
 *     &lt;enumeration value="PASTDUE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProcessDocumentStatus")
@XmlEnum
public enum ProcessDocumentStatus {

    APPROVED,
    WAITINGRESPONSE,
    DENIED,
    PASTDUE;

    public String value() {
        return name();
    }

    public static ProcessDocumentStatus fromValue(String v) {
        return valueOf(v);
    }

}
